### ISSUE TITLE
大佬有计划支持国服6.0版本吗？

### ISSUE THREAD

**Issue by AnnAngela** [CillinjoLo/ErozeaZoom#1]
@CillinjoLo 如果需要帮助的话，可以告诉我如何获取StructureAddress等，我愿意提供帮助

**Comment by idenpa** [comment]
作者估计最近很忙  还是自己动手吧
1E74290  2022.02.25.0000.0000

**Comment by AnnAngela** [comment]
> 1E74290 2022.02.25.0000.0000

感谢，不过我想问问这个是如何获取的，我想学习一下以后也可以提供帮助 @idenpa

**Comment by idenpa** [comment]
> > 1E74290 2022.02.25.0000.0000
> 
> 感谢，不过我想问问这个是如何获取的，我想学习一下以后也可以提供帮助 @idenpa

那你给我来个邮箱 我把教程发给你吧 还是很好找的 有CE就行

**Comment by AnnAngela** [comment]
> > > 1E74290 2022.02.25.0000.0000
> > 
> > 
> > 感谢，不过我想问问这个是如何获取的，我想学习一下以后也可以提供帮助 @idenpa
> 
> 那你给我来个邮箱 我把教程发给你吧 还是很好找的 有CE就行

naganjue%vip.qq.com，麻烦大佬了

**Comment by Ultramanonlythreeminutes** [comment]
大佬麻烦给我也发份教程谢谢！  kissinthegalaxy@outlook.com

**Comment by RingTure** [comment]
> 求教程，感谢！fantasyofdawnzym@gmail.com

**Comment by idenpa** [comment]
上面2位，给你们发邮件了哦

**Comment by Ultramanonlythreeminutes** [comment]
> 上面2位，给你们发邮件了哦

谢谢~ 笔芯~！

**Comment by mercilessfrost** [comment]
同求教程，感谢 mercilesssun@gmail.com
